### ISSUE TITLE
Графика - размер ячеек

### ISSUE THREAD

**Issue by IrinaMank** [IrinaMank/slae-project#12]
Насколько реализуем автоподбор размера ячейки под выбранный формат числа? Или ресурсы, потраченные на реализацию такой фичи, не сопоставимы с ее пользой,  и стоит оставить эту обязанность на пользователе?
![32](https://user-images.githubusercontent.com/23400308/36354395-3ef48f92-1506-11e8-8879-eebbfa75a43c.png)

**Comment by dd84ai** [comment]
Момент, сейчас подумаю....
Единственная проблема чтобы это сделать это DrawText измерить в пикселях размеры рисуемые этой функцией. 

Функция данная предоставлена от SharpGL

И решением данной проблемой было бы три варианта
1) Обнаружить вдруг есть способ чтобы данная функция как то сообщает(вытащить) с какой шириной высотой она рисует благодаря своим создателям(Идеальный вариант решения, пока не реализуем ибо нигде в явном виде не даны эти данные)
2) Реализовывать самому аналог данной функции рисование текста.... весьма затратно но попытаться можно. Придется шрифты скачивать, настраивать и тд...(Затратно по силам, по сложности настроек и по качеству получаемого результата)
3) Попробовать грубый вариант извлечения рисуемых границ какой нить найти(Возможны высокие повышение нагрузки)
4) О в принципе есть более простой вариант решения. Мы можем упростить ситуацию и взяв какую то широкую цифру взять её за стандарт ширины символа. Потом измерить для данных 30 размеров шрифта размер данного символа в пикселях
И теперь уже мы можем посчитать для любого количества символов рисуемых DrawText(по крайней мере для цифр) достаточно точно ширину в пикселях! (Аналогично высоту в пикселях)
А это уже позволит автоподбор ширины/высоты ячейки без проблем.
Данный вариант не повысит нагрузки.

Ответ: Да, решаемо. Простой вариант решения данной проблемы найден. 4 вариант вполне подходит.

**Comment by IrinaMank** [comment]
Отлично! Спасибо за оперативность. Думаю, стоит добавить такую функцию, раз реализуется она просто, - она довольно удобная.
