### ISSUE TITLE
Графика

### ISSUE THREAD

**Issue by IrinaMank** [IrinaMank/slae-project#29]
Вижу либо это, либо, когда закрываю все кроме вижуалки,  просто зависает надолго (пока не кончается мое терпение и я не прерываю дебаг)
Учитывая, что системные характеристики компьютера у меня не самые слабые, такое подвисание вряд ли нормально.
![35](https://user-images.githubusercontent.com/23400308/36643872-298380ae-1a84-11e8-8ed1-427eef2ac2cc.png)

**Comment by dd84ai** [comment]
Мего большой тест на проверку самосхлопывания забыл выключить

**Comment by dd84ai** [comment]
Момент, сейчас карьеру

**Comment by dd84ai** [comment]
Уберу*

**Comment by dd84ai** [comment]
https://github.com/IrinaMank/slae-project/pull/30
фиксик
