### ISSUE TITLE
ЮИ баги

### ISSUE THREAD

**Issue by IrinaMank** [IrinaMank/slae-project#72]
![image](https://user-images.githubusercontent.com/23400308/37824511-76bbdb60-2ebf-11e8-8183-d9db8eb852cf.png)
1. Исправить на растягивание картинки при полноэкранном формате и сделать центрирование/растягивание 
![image](https://user-images.githubusercontent.com/23400308/37824574-a89142d8-2ebf-11e8-82de-b46687a6a3a0.png)
2.  Исправить эксепшн при повторном выборе файла. То же самое в ручном вводе, если нажать назад и ввести другую матрицу

**Comment by Novemb3r** [comment]
#2 фиксед

**Comment by Novemb3r** [comment]
#1 фиксед
